name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build admin-panel
        run: |
          cd admin-panel
          npm ci
          npm run build

      - name: Deploy admin-panel
        run: |
          cd admin-panel
          firebase deploy --only hosting:admin-panel --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Build user-interface
        run: |
          cd user-interface
          npm ci
          npm run build

      - name: Deploy user-interface
        run: |
          cd user-interface
          firebase deploy --only hosting:user-interface --token ${{ secrets.FIREBASE_TOKEN }}
