# firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy admin-panel
        run: |
          cd admin-panel
          npm ci
          npm run build
          firebase deploy --project admin-panel --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Build and deploy user-interface
        run: |
          cd user-interface
          npm ci
          npm run build
          firebase deploy --project user-interface --token ${{ secrets.FIREBASE_TOKEN }}
